services:
  frontend:
    image: vacancy-frontend
    build:
      context: ./frontend
    expose:
      - 3000
    networks:
      - app-network

  backend:
    image: vacancy-backend
    build:
      context: ./backend
    expose:
      - 8000
    networks:
      - app-network
    env_file:
      - "./backend/.env"
    environment:
      ENV_MODE: "prod"

  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
