export { default as PlusSVG } from "@/app/components/svgs/plus.svg";
export { default as MinusSVG } from "@/app/components/svgs/minus.svg";
export { default as HeaderSVG } from "@/app/components/svgs/header.svg";
export { default as EditSVG } from "@/app/components/svgs/edit.svg";
export { default as CopySVG } from "@/app/components/svgs/copy.svg";
export { default as TrashSVG } from "@/app/components/svgs/trash.svg";
export { default as CompanyNotFound } from "@/app/components/svgs/companyNotFound.svg";
export { default as Filter } from "@/app/components/svgs/filter.svg";
export { default as Close } from "@/app/components/svgs/close.svg";
